# Generated by Django 5.1.1 on 2024-10-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
